name: Push documentation to docs repo

on:
  push:
    tags:
      - v1.*

jobs:
  push-to-docs:
    uses: nevermined-io/reusable-workflows/.github/workflows/push-to-docs.yml@main
    with:
      path-to-push: external/gateway
    secrets: inherit
