# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start Nevermined
      run: |
        docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
        git clone https://github.com/keyko-io/nevermined-tools
        cd nevermined-tools
        rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"
        bash start_nevermined.sh --no-commons --no-gateway --ldap --latest 2>&1 > start_nevermined.log &
        cd ..
        for i in $(seq 1 50); do
          sleep 5
          [ -f "${HOME}/.nevermined/nvermined-contracts/artifacts/ready" ] && break
        done
        ls -la "${HOME}/.nevermined/nevermined-contracts/artifacts/"
        ./scripts/wait_for_migration_and_extract_keeper_artifacts.sh
    - name: Install python package
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Test with pytest
      run: |
        export PROVIDER_ADDRESS=0x00bd138abd70e2f00903268f3db08f2d25677c9e
        export PROVIDER_PASSWORD=node0
        export PROVIDER_KEYFILE=tests/resources/data/publisher_key_file.json
        export RSA_PRIVKEY_FILE=tests/resources/data/rsa_priv_key.pem
        export RSA_PUBKEY_FILE=tests/resources/data/rsa_pub_key.pem

        pytest -v
